### ISSUE TITLE
[error] (run-main-0) java.util.NoSuchElementException: head of empty array

### ISSUE THREAD

**Issue by oratosa** [nasa-jpl-cord-19/covid19-knowledge-graph#4]
I tried both of patterns to run the program but I got failed the running.
I would like some advice if you know any solution. 

What I did is as below:

* From sbt
  * command
  sbt:covid19_knowledge_graph> run /home/taroaso/covid19-knowledge-graph/data/CORD-19_files/comm_use_subset /home/taroaso/covid19-knowledge-graph/data/annie_extraction_files
  * result
  [info] running gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph /home/taroaso/covid19-knowledge-graph/data/CORD-19_files/comm_use_subset /home/taroaso/covid19-knowledge-graph/data/annie_extraction_files
      loading 
[error] (run-main-0) java.util.NoSuchElementException: head of empty array
[error] java.util.NoSuchElementException: head of empty array
[error]         at scala.collection.ArrayOps$.head$extension(ArrayOps.scala:222)
[error]         at gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph$.loadAFileJSON(covid19_knowledge_graph.scala:76)
[error] 	at gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph$.$anonfun$main$3(covid19_knowledge_graph.scala:39)
[error] 	at gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph$.$anonfun$main$3$adapted(covid19_knowledge_graph.scala:38)
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] 	at gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph$.main(covid19_knowledge_graph.scala:38)
[error] 	at gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph$.main(covid19_knowledge_graph.scala:16)
[error] 	at gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph.main(covid19_knowledge_graph.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1

* As a standalone JAR
  * command
  java -jar ./target/scala-2.13/covid19_knowledge_graph-assembly-0.1.0-SNAPSHOT.jar '/home/taroaso/covid19-knowledge-graph/data/CORD-19_files/comm_use_subset' '/home/taroaso/covid19-knowledge-graph/data/annie_extraction_files'
  * result
        loading 
Exception in thread "main" java.util.NoSuchElementException: head of empty array
	at scala.collection.ArrayOps$.head$extension(ArrayOps.scala:222)
	at gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph$.loadAFileJSON(covid19_knowledge_graph.scala:76)
	at gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph$.$anonfun$main$3(covid19_knowledge_graph.scala:39)
	at gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph$.$anonfun$main$3$adapted(covid19_knowledge_graph.scala:38)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph$.main(covid19_knowledge_graph.scala:38)
	at gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph$.main(covid19_knowledge_graph.scala:16)
	at gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph.main(covid19_knowledge_graph.scala)

**Comment by lewismc** [comment]
Hi @oratosa I apologize for the late reply. I was very busy.
First thing first, please ensure you are using master branch. 
Secondly, make sure you have the OpenIE server running on `localhost:8000`

The `NoSuchElementException` indicates to me that your input data is not structured properly. For example, when I run the following, I am able to iteratively process the files without issue.
```
sbt:covid19_knowledge_graph> run /Users/lmcgibbn/Downloads/covid19-knowledge-graph/data/comm_use_subset /Users/lmcgibbn/Downloads/covid19-knowledge-graph/data/scispacy/individual_files
[info] running gov.nasa.jpl.covid19_knowledge_graph.covid19_knowledge_graph /Users/lmcgibbn/Downloads/covid19-knowledge-graph/data/comm_use_subset /Users/lmcgibbn/Downloads/covid19-knowledge-graph/data/scispacy/individual_files
      loading /Users/lmcgibbn/Downloads/covid19-knowledge-graph/data/scispacy/individual_files/000b7d1517ceebb34e1e3e817695b6de03e2fa78.json
  loading /Users/lmcgibbn/Downloads/covid19-knowledge-graph/data/comm_use_subset/000b7d1517ceebb34e1e3e817695b6de03e2fa78.json
...
```

Do you have the scispacy dataset as your second parameter?
